version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  cloudband:
    image: cloudband
    container_name: cloudband
    ports:
      - 3000:3000
    command: npm run start
networks:
  app:


